FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:0ef315bdcbb0837a5315d209b0590e081c93012bf339eabc7ddb35f141443987

USER 0
COPY showroom /bundle/showroom
COPY showroom-content/entrypoint.sh /content-entrypoint.sh
RUN chmod 0755 /content-entrypoint.sh \
    && chown -R 1001:0 /bundle
USER 1001

ENTRYPOINT ["/content-entrypoint.sh"]
