apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-analysis-adapter
  labels:
    {{- include "virtualization-ai.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualization-ai-presentation
  labels:
    {{- include "virtualization-ai.labels" . | nindent 4 }}
automountServiceAccountToken: false
